# Generated by Django 5.1.1 on 2024-10-24 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(default=datetime.timezone)),
                ('status', models.CharField(choices=[('com', 'Completed'), ('inp', 'In Progress'), ('fld', 'Failed')], max_length=200)),
            ],
        ),
    ]
